### ISSUE TITLE
Browserify transforms support

### ISSUE THREAD

**Issue by guybedford** [jspm/npm#10]
This needs to be investigated for feasibility.

**Comment by trusktr** [comment]
This will be really cool. One of the main things I'd use this for is to apply `glslify` onto WebGL shader files. Glslify adds CommonJS-style imports/exports to GLSL files.

**Comment by trusktr** [comment]
Support for Webpack loaders would be cool too.

**Comment by myitcv** [comment]
:+1: on the back of https://github.com/plotly/plotly.js/issues/22

**Comment by guybedford** [comment]
This seems like it isn't going to be a huge priority as browserify transforms aren't that common.

**Comment by trusktr** [comment]
@guybedford Browserify has 2,190,020 downloads in the last month, so it seems browserify transforms  would be fairly common when compared to any other build tools plugins.
