### ISSUE TITLE
jspm tries to download a wrong version when resolving dependencies

### ISSUE THREAD

**Issue by niieani** [jspm/npm#104]
Hello everybody,
I'm trying to install https://github.com/mikemintz/rethinkdb-websocket-client via jspm, but jspm complains that:

```
err  Installing npm:rethinkdb-websocket-client@0.4.3, no version match for npm:node-libs-browser@0.6.0
```

Even though the package defines node-libs-browser as:
```
    "node-libs-browser": ">= 0.4.0 <=0.6.0",
```

The package installs properly via npm.

**Comment by guybedford** [comment]
Thanks, yes this is actually a relatively common issue, and a bug in jspm.

You can fix this manually by altering the config.js file map to use the right version of `node-libs-browser` that you want.

For the actual root cause fix, I've created https://github.com/jspm/jspm-cli/issues/1253.
