### ISSUE TITLE
Error using apeman-react-image

### ISSUE THREAD

**Issue by tyrsius** [jspm/npm#113]
after installing with `jspm installl npm:apeman-react-image", I tried importing the package into an ES6 compiled app with a standard `import` (as I have done for every other jspm installed package). I get the errors:
```
Uncaught SyntaxError: Unexpected token <J @ system.src.js:4703r.execute @ system.src.js:4703i @ system.src.js:4703n @ system.src.js:4703execute @ system.src.js:4703y @ system.src.js:4703w @ system.src.js:4703p @ system.src.js:4703h @ system.src.js:4703(anonymous function) @ system.src.js:4703
swc:1 Uncaught (in promise) Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:9000/jspm_packages/npm/apeman-react-image@1.0.1.js
	Error loading http://localhost:9000/main.js
```

I noticed that the request to `jspm_packages/npm/apeman-react-image@1.0.1.js` is a non-existent file. It was not installed into the `npm` directory, the way most npm libraries do (with those single line `module.exports` scripts)

**Comment by guybedford** [comment]
If the main entry point file was not created that means that no `main` was found. Does the file at `jspm_packages/npm/apeman-react-image@1.0.1/package.json` have a main property specified?

**Comment by guybedford** [comment]
Looking at https://github.com/apeman-react-labo/apeman-react-image it does. This is a bug then and I believe was the same one just resolved in https://github.com/jspm/jspm-cli/issues/1387.

**Comment by tyrsius** [comment]
Sweet. Is there an update schedule, or do you know when this fix is going out?
