### ISSUE TITLE
Check download size against maxRepoSize npm registry config

### ISSUE THREAD

**Issue by blackxored** [jspm/npm#116]
Checks on `lib/npm.js` prevent the latest emojione from being installed, apparently due to response/package size. I've locally fixed it but not sure how it would affect remote installs.

**Comment by guybedford** [comment]
@blackxored sure we should replace this with a check to the `maxRepoSize` configuration option passed into the constructor options.

**Comment by blackxored** [comment]
Any progress on this. Trying to rebuild my project under a Docker env since a long time, and almost forgot the local fix :D

**Comment by guybedford** [comment]
PRs welcome!
