### ISSUE TITLE
Error on lookup for scoped packages (Invalid status code 503)

### ISSUE THREAD

**Issue by teohhanhui** [jspm/npm#117]
with jspm 0.16.19

```
warn Error on lookup for npm:@cycle/fetch
     Invalid status code 503

err  Error looking up npm:@cycle/fetch.
```

It was working before... And just stopped working with no changes on my end.

**Comment by teohhanhui** [comment]
It seems to work sometimes... Is this an npm registry issue?

**Comment by guybedford** [comment]
Yes this would be due to instability in the npm registry (500 error and all).

**Comment by teohhanhui** [comment]
For those who were wondering:

>
#### Jan 27, 2016
Intermittent scoped module installation failures from US East
The registry was returning elevated rates of 503s from a specific origin host that US East users were likely to be routed to. This was due to a misconfiguration that caused requests to an internal service to be rejected. This configuration has been corrected. 503 rates are back down to normal. 
*Jan 27, 17:31 UTC*

http://status.npmjs.org/
