### ISSUE TITLE
Sourcemaps for commonjs modules are lost during conversion

### ISSUE THREAD

**Issue by pawsong** [jspm/npm#118]
In this line:

https://github.com/jspm/npm/blob/master/lib/node-conversion.js#L195

traceur compiler in `system-builder` seems to remove the comment that indicates sourcemap location during compiliation. Is there any simple workaround?

**Comment by guybedford** [comment]
This is fixed in the 0.17 beta, perhaps try that version.

**Comment by pawsong** [comment]
Thank you for quick reply!
