### ISSUE TITLE
The index.js not available when installing npm:angular-ui-bootstrap with jspm

### ISSUE THREAD

**Issue by jjmurre** [jspm/npm#119]
After installing angular-ui-bootstrap with jspm the 'index.js' is missing from the top-level dir of 'angular-ui-bootstrap'.

When installing with npm contents of this top-level dir is:

- CHANGELOG.md  
- dist  
- index.js  
- LICENSE  
- package.json  
- README.md  
- src  
- template

jspm only installs:
- dist  
- package.json  
- src  
- template

**Comment by guybedford** [comment]
Are there `files` or `ignore` properties in the package.json? If so it would jspm respecting those.

**Comment by jjmurre** [comment]
There is a 'files' property:

"files": [
    "dist/",
    "src/",
    "template/"
  ],
So I guess I have to ask them to add 'index.js' into this property. I file an issue in their tracker.
Tx. for your quick response.
