### ISSUE TITLE
jspm installs different files than npm

### ISSUE THREAD

**Issue by jaroslavrehorka** [jspm/npm#127]
Hi, I've strange problem with library [knexjs](https://github.com/tgriesser/knex) (query builder),
when I run `jspm install npm:knex` it installs files with different content _(e.g. src/client.js)_ compared to same files installed with `npm install knex`. 
I believe both versions should be the same (0.10.0) but jspm's version is different and content of all folders in **lib** or **src** folders is missing.

Any ideas where is the problem?
Thanks

**Comment by guybedford** [comment]
Thanks, I've added a fix for this in jspm 0.17 in https://github.com/jspm/jspm-cli/commit/ec01fef473b770680acab064ce8eb91e2fea4746.

**Comment by jaroslavrehorka** [comment]
Thank's, unfortunately this did help just partly, It does copy all dirs correctly but files in those dirs are missing

**Comment by guybedford** [comment]
Because of the cache, you'll need to install with `jspm install npm:knex -f` to test this out properly.

**Comment by jaroslavrehorka** [comment]
thanks, it works properly now =)
