### ISSUE TITLE
Timing out when trying to access a module on npm.jspm.io

### ISSUE THREAD

**Issue by cheapsteak** [jspm/npm#128]
Hopefully this is the right place

https://npm.jspm.io/sass.js@0.9/dist/sass.js

^ Hitting this address will currently result in the browser doing nothing for a very long time then timing out

Steps to reproduce is trying to use jspm to map scss files using theefer/plugin-sass

```
'scss': 'github:theefer/plugin-sass',
```

This will trigger a series of network requests that result in  a timeout upon hitting the sass.js on npm.jspm.io

![image](https://cloud.githubusercontent.com/assets/743976/13769713/3d4de402-ea58-11e5-8898-b90d7915fa31.png)

Can reproduce here
http://plnkr.co/edit/dYcW8DsDF0GyT0SLef45

**Comment by guybedford** [comment]
Thanks for reporting, yes some packages do time out when processing on the CDN. Fixing this specific timeout is going to be difficult to prioritise as the next thing to work on is upgrading the CDN to the 0.17 version of jspm, which should then naturally resolve this anyway.
