### ISSUE TITLE
Apply "jspm" properties only in github dependencies

### ISSUE THREAD

**Issue by neothemachine** [jspm/npm#131]
It seems when installing an npm package via jspm that it actually looks at the `"jspm"` package.json property of that npm package. Is that on purpose? I thought this is really for jspm/github installs. The problem is that the folder structure is different for the npm-published version (/lib vs /src due to transpilation), and the npm versions don't contain the /src folder, whereas the github repo doesn't contain the /lib folder. I wanted to be able to install the package (I'm the developer) both via the npm releases but also directly from github, therefore I tried to fix that by overriding `"main"` and `"files"` within `"jspm"`, but now this gets used in npm installs as well.

Is this what `jspmNodeConversion: false` is for? I'm not sure what that covers exactly, that is, if it disables *any* jspm specific fields or overrides, or if it just doesn't run npm conversions. If this is not the solution, is there any? Except removing the `"jspm"` block for the npm releases, since that would be a bit annoying.

**Comment by guybedford** [comment]
The jspm property applies to all registries. It's usually best to pick one of npm or github to support, otherwise perhaps look at ways of altering the published package.json that goes to npm.
