### ISSUE TITLE
Upgrade graceful-fs to 4.x

### ISSUE THREAD

**Issue by ppitonak** [jspm/npm#132]
When running _npm install_, console log shows this warning:

    npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

**Comment by guybedford** [comment]
We've upgraded to graceful-fs 4 so it sounds like this is entirely due to https://github.com/jspm/npm/issues/114. Note that the graceful-fs deprecation is a very slow deprecation, so there's nothing to worry about for at least a few months. The fix will be in soon.

**Comment by guybedford** [comment]
Yes, this needs to be done on the jspm 0.16 branch.
