### ISSUE TITLE
cant install mapbox-gl

### ISSUE THREAD

**Issue by dtaalbers** [jspm/npm#135]
I am unable to install it via 

`jspm install npm:mapbox-gl`

I am running `jspm 0.16.36`

``` 
     Looking up npm:mapbox-gl
     Updating registry cache...
     Downloading npm:mapbox-gl@0.19.1

warn Error on processPackageConfig
     Package.json dependency mapbox-gl-shaders set to github:mapbox/mapbox-gl-shaders#e4737bb136d718f9c5fe8d943380f05db6249b57, which is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.

warn Error processing package config for npm:mapbox-gl.

err  Error processing package config for npm:mapbox-gl.

warn Installation changes not saved.
```

It works via `npm install mapbox-gl` though. Any suggestions?

**Comment by guybedford** [comment]
Unfortunately we don't support installing github repos to individual commit hashes in jspm, so this isn't possible.

**Comment by guybedford** [comment]
There was actually a bug here in https://github.com/jspm/npm/commit/98eff5faa9c2e8c65534c3ce8206227627d87f9f. But the commit hashes issue isn't something we can easily support unfortunately.
