### ISSUE TITLE
Error on lookup for npm:@angular/... - Invalid status code 500

### ISSUE THREAD

**Issue by lukaszczerpak** [jspm/npm#136]
I am not able to complete `jspm update` since it stops in the middle and throws the following error:

```
...
ok   Installed npm:rxjs@5.0.0-beta.6 (5.0.0-beta.6)
ok   Installed @angular/http as npm:@angular/http@^2.0.0-rc.1 (2.0.0-rc.1)
ok   Installed @angular/core as npm:@angular/core@^2.0.0-rc.1 (2.0.0-rc.1)

warn Error on lookup for npm:@angular/upgrade
     Invalid status code 500

err  Error looking up npm:@angular/upgrade.

warn Installation changes not saved.
```

It started to happen recently and since then never completed successfully. Maybe it's a coincidence, but it stops at `@angular` packages most of time. Not sure what's going on and how to fix it. Any help would be much appreciated.

Let me know if any other information is needed to track it down, here are node/npm versions:

node v4.4.5
npm  v3.9.5
jspm 0.16.39

**Comment by gregcummines** [comment]
I just started seeing this today as well. 

jspm install npm:@angular/core
     Looking up npm:@angular/core

warn Error on lookup for npm:@angular/core
     Invalid status code 500

err  Error looking up npm:@angular/core.

warn Installation changes not saved.

**Comment by musabhusaini** [comment]
I am seeing this as well.

node v6.2.1
npm v3.9.3
jspm v0.17.0-beta.21

**Comment by jakeNiemiec** [comment]
+1 Related: https://github.com/jspm/jspm-cli/issues/1910

**Comment by jakeNiemiec** [comment]
See: https://gitter.im/jspm/jspm?at=575f22466092456f6633da6c

1000 curl requests to https://registry.npmjs.org/angular returns:

- 1000 `http_status: 200`


1000 curl requests to  https://registry.npmjs.org/@angular%2Fupgrade returns:

- 730 `http_status: 401`
- 248 `http_status: 500`
- 22 `http_status: 200`
- Total = 1000

This is reasonable proof that **this is an npm hosting problem**.

**Comment by jakeNiemiec** [comment]
For those subscribed: Everything seems to work more often if you are logged in to `npm login`. I can now run `jspm install`.

**Comment by laurelnaiad** [comment]
That does seem to get me working again. Thanks @jakeNiemiec . I hope that's not the end of this subject, though. Something fishy here.

**Comment by guybedford** [comment]
Closing as it's sounds like this is resolved.
