### ISSUE TITLE
Package doesn't install correctly.

### ISSUE THREAD

**Issue by fa7ad** [jspm/npm#142]
I tried to install [github-api](https://www.npmjs.com/package/github-api) from npm.
The CLI finishes the installation without error, but I get a 404 when I try to load the page in browser.
So, I did some digging and the problem seems to be that jspm alters the directory structure when it installs the package.

the package's package.json says
```json
"main": "./dist/components/GitHub.js"
```

but the jspm installation structure doesn't contain those files
![screenshot from 2016-07-21 09-44-53](https://cloud.githubusercontent.com/assets/7447677/17010665/dbf1a164-4f27-11e6-8b87-1f23ceb629cf.png)

and this how npm structures it
![screenshot from 2016-07-21 09-46-26](https://cloud.githubusercontent.com/assets/7447677/17010692/0bb2052e-4f28-11e6-850c-8638e5b2bbc8.png)

**Comment by guybedford** [comment]
Try running `jspm install npm:github-api -o "{files:null}"`. The issue is that the entry for `dist/*` is only treated as a first-level wildcard in jspm while in npm it is treated as a deep wildcard. I've created https://github.com/jspm/npm/issues/143 to track.
