### ISSUE TITLE
0.29.5 fails to resolve on npm

### ISSUE THREAD

**Issue by larsthorup** [jspm/npm#151]
>npm install jspm-npm --save
    npm ERR! fetch failed https://registry.npmjs.org/jspm-npm/-/jspm-npm-0.29.5.tgz

Trying to download `https://registry.npmjs.org/jspm-npm/-/jspm-npm-0.29.5.tgz`, gives me:

    {"code":"InternalError","message":"Cannot read property '0.29.5' of undefined"}

Something wrong with the recent publish?

This breaks `postcss-import`

**Comment by guybedford** [comment]
It sounds like this was an npm issue. Pushed a 0.29.6 that seems to work now.

**Comment by larsthorup** [comment]
Yes, it works. Thanks!
