### ISSUE TITLE
source modifications -> config maps

### ISSUE THREAD

**Issue by alexisvincent** [jspm/npm#158]
@guybedford How possible do you think it would be to, instead of performing package conversions (source changes and new files), generate SystemJS config files that achieve the same thing?

I'm not nessasarily asking for JSPM itself, but more because I'm trying to work out how viable it is to build a tool that leaves node packages unchanged, but spits out a config that makes it work.

**Comment by guybedford** [comment]
@alexisvincent in jspm 0.17, we don't modify the files at all, and only generate package configuration files for SystemJS already.

**Comment by alexisvincent** [comment]
@guybedford Where can I find the code to do this? In this repository or in jspm-cli?

**Comment by guybedford** [comment]
It's the conversion code in https://github.com/jspm/npm/blob/0.17/lib/node-conversion.js.

**Comment by alexisvincent** [comment]
@guybedford Thanks! I was reading the master branch!
