### ISSUE TITLE
Include __filename and __dirname support

### ISSUE THREAD

**Issue by guybedford** [jspm/npm#16]
Then it can be removed from SystemJS builder.

**Comment by lig** [comment]
Well. The is here. What should one do to avoid this issue?

**Comment by guybedford** [comment]
@lig the SystemJS CommonJS module format comes with full support for this. Make sure the module in question is loading as a CommonJS module (`"format cjs";` at the top of the file or `System.config({ meta: { 'path/to/file.js': { format: 'cjs' } } })`). Otherwise it may help to hear your exact issue here.

**Comment by lig** [comment]
Just filed my problem here https://github.com/brianc/node-postgres/issues/816
