### ISSUE TITLE
Error on getOverride for jspm:npm

### ISSUE THREAD

**Issue by priyabrat1801** [jspm/npm#176]
Getting the below error while doing jspm install
  
     warn Error on getOverride for jspm:npm
          TypeError: "timeout" must be an unsigned integer
           at validateTimeout (child_process.js:623:11)
           at Object.exports.execFile (child_process.js:202:3)
           at exports.exec (child_process.js:139:18)

node: 9.4.0
npm: 5.6.0
jspm: 0.16.55

**Comment by guybedford** [comment]
Which version of `jspm-npm` are you using here? (from `jspm/node_modules/jspm-npm`)

Make sure the latest version is installed.

**Comment by guybedford** [comment]
Also `jspm-registry` should be at version 0.4.4.

**Comment by priyabrat1801** [comment]
jspm-npm: 0.26.13
jspm-registry: 0.4.3

We are not installing these exclusively in package.json. Guess this is coming from the dependency on jspm package itself. Will it help to add these exclusively in the package.json?

**Comment by guybedford** [comment]
The problem is exactly not using 0.4.4 of jspm-registry. Npm should install
the latest version by default, otherwise you should be able to just do the
update manually.

**Comment by priyabrat1801** [comment]
Yes, we are using yarn and seems the versions were cached in the lock file and was not updating to the latest versions. We changed it to do the npm install and seems to be working.

Thanks @guybedford for the fix. we will check on the yarn issue separately.

**Comment by priyabrat1801** [comment]
Closing for now.
