### ISSUE TITLE
Challenge: get express server working through jspm run

### ISSUE THREAD

**Issue by guybedford** [jspm/npm#26]
//cc @bubblyworld

**Comment by dvc94ch** [comment]
When running express using jspm run __dirname is set to /dvc/workspace/... instead of /home/dvc/workspace/...
When I do npm install express && node server.js, __dirname is set to  /home/dvc/workspace/...

**Comment by guybedford** [comment]
@dvc94ch thanks - yes this is an issue. `__dirname` is set to the directory of the current module instead of the baseURI. Created https://github.com/systemjs/systemjs/issues/519.

**Comment by guybedford** [comment]
@dvc94ch are you running in Node with `window` defined by any chance?

**Comment by dvc94ch** [comment]
No I'm not. Just checked to be sure.

I'm using ```iojs 2.3.0``` in case it's relevant.

**Comment by guybedford** [comment]
It's definitely working fine for me in iojs - this must be some more complex interaction happening somewhere then.

**Comment by dvc94ch** [comment]
Steps to reproduce on Linux:

```
mkdir test-dirname
cd test-dirname
echo "var express =
require('express');console.log(__dirname);console.log(window);" > server.js
jspm install npm:express
edit package.json to use npm:express@^4.12.4 instead of 5.0.0alpha1
rm -r jspm_packages
rm config.js
jspm install
jspm run server
```
```
[dvc@system76 test-dirname]$ jspm run server
/dvc/workspace/test-dirname

err  file:/home/dvc/workspace/test-dirname/server.js:3
     console.log(window);
            ^
     ReferenceError: window is not defined
         at Object.<anonymous>
(file:/home/dvc/workspace/test-dirname/server.js:3:13)
         at file:/home/dvc/workspace/test-dirname/server.js:5:4
         at Object.exports.runInThisContext (vm.js:54:17)
         at doEval
(/usr/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:2400:10)
         at __eval
(/usr/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:2317:7)
         at Loader.exec [as __exec]
(/usr/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:339:5)
         at load.metadata.execute
(/usr/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1222:16)
         at linkDynamicModule
(/usr/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:669:32)
         at link
(/usr/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:528:11)
         at Object.execute
(/usr/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:852:11)
```
Am I doing something wrong? Are you getting a different result?

**Comment by guybedford** [comment]
Note that running express through jspm as described here was a stretch challenge, and not part of the core API. That is fixing these issues is not within the current priorities (see https://github.com/jspm/jspm-cli/wiki/NodeJS-Usage). It will be though eventually, but it's just not where the focus is currently.

That said, if you're interested into looking into the root cause here it would certainly be useful to work out the bug / override to fix this.

**Comment by dvc94ch** [comment]
I'll have some time tomorrow to debug this, I'll report if I find anything.
So could you reproduce this? Or is it a problem on my end somewhere?

**Comment by guybedford** [comment]
The issue I get running on jspm 0.16 beta is:

```
createCredentials() is deprecated, use tls.createSecureContext instead
Credentials is deprecated, use tls.createSecureContext instead

err  /Users/guybedford/Projects/systemjs/dist/system.src.js:1205
        throw addToError(e, 'Evaluating ' + load.address);
              ^
/Users/guybedford/Projects/systemjs/dist/system.src.js:1205
        throw addToError(e, 'Evaluating ' + load.address);
              ^
/Users/guybedford/Projects/systemjs/dist/system.src.js:1205
        throw addToError(e, 'Evaluating ' + load.address);
              ^
     file:///Users/guybedford/Projects/jspm-cli/sandbox/jspm_packages/npm/express@4.12.4/lib/request.js:66
```

**Comment by guybedford** [comment]
Here's the updated error with error-handling actually working - 

```
createCredentials() is deprecated, use tls.createSecureContext instead
Credentials is deprecated, use tls.createSecureContext instead

/Users/guybedford/Projects/systemjs/dist/system.src.js:1205
        throw addToError(e.toString(), 'Evaluating ' + load.address);
              ^

err  TypeError: file:///Users/guybedford/Projects/jspm-cli/sandbox/jspm_packages/npm/express@4.12.4/lib/request.js:66
       var proto = this.connection.encrypted ? 'https' : 'http';
                             ^
     Cannot read property 'encrypted' of undefined
	Evaluating file:///Users/guybedford/Projects/jspm-cli/sandbox/jspm_packages/npm/express@4.12.4/lib/express.js
	Evaluating file:///Users/guybedford/Projects/jspm-cli/sandbox/jspm_packages/npm/express@4.12.4/index.js
	Evaluating file:///Users/guybedford/Projects/jspm-cli/sandbox/jspm_packages/npm/express@4.12.4.js
	Evaluating file:///Users/guybedford/Projects/jspm-cli/sandbox/server.js
	Error loading file:///Users/guybedford/Projects/jspm-cli/sandbox/server.js
```

**Comment by dvc94ch** [comment]
This issue is fixed in express 5.0.0-alpha-1. Now there's still the issue I
originaly reported with the __dirname not set correctly. With jspm@0.16.beta
it's set to home/dvc/workspace/... so it's only missing the leading slash.
This affects express since it's trying to load files with the wrong path.

```
 Error: ENOENT: no such file or directory, open
'home/dvc/workspace/test-dirname/jspm_packages/npm/mime@1.2.11
/types/mime.types'
         at Error (native)
         at Object.fs.openSync (fs.js:549:18)
         at Object.fs.readFileSync (fs.js:397:15)
         at Mime.load
(file:///home/dvc/workspace/test-dirname/jspm_packages/npm/mime@1.2.11
/mime.js:26:22)
         at
file:///home/dvc/workspace/test-dirname/jspm_packages/npm/mime@1.2.11
/mime.js:44:8
         at Object.<anonymous>
(file:///home/dvc/workspace/test-dirname/jspm_packages/npm/mime@1.2.11
/mime.js:52:3)
         at
file:///home/dvc/workspace/test-dirname/jspm_packages/npm/mime@1.2.11
/mime.js:54:4
         at Object.exports.runInThisContext (vm.js:54:17)
         at SystemJSNodeLoader.__exec
(/usr/local/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1193:12)
         at load.metadata.execute
(/usr/local/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:2425:18)
```

**Comment by guybedford** [comment]
Ahh right, that leading slash issue I actually fixed in https://github.com/systemjs/systemjs/commit/f949ed11612851e12403e61007c60c81a09f65f5 I believe. Let me know if its still not behaving correctly though.

**Comment by dvc94ch** [comment]
Since you're a few steps ahead of me :) what's the fix for

```
TypeError: baseURL should only be configured once and must be configured
first.
         at SystemJSNodeLoader.SystemJSLoader.config
(/home/dvc/workspace/test-dirname/node_modules/systemjs/dist/system.src.js:1378:15)
         at
/home/dvc/workspace/test-dirname/node_modules/jspm/lib/core.js:57:12
         at process._tickCallback (node.js:357:9)
         at Function.Module.runMain (module.js:469:11)
         at startup (node.js:117:18)
         at node.js:948:3
```
in https://github.com/systemjs/systemjs/blob/master/lib/core.js

**Comment by guybedford** [comment]
It depends how you are running your build? Basically `baseURL` needs to be set before any other configuration.

**Comment by dvc94ch** [comment]
I took a quick look in systemjs config api, node globals and package.json
spec and didn't see ```baseURL``` mentioned anywhere. What's ```baseURL```?

**Comment by guybedford** [comment]
baseURL is the reference point for bundling, so that bundle names can be portable.

This may be a jspm bug - how are you running the bundling process?

**Comment by dvc94ch** [comment]
I'm not I'm just running ```jspm run server``` and that does
System.import('server'); so it doesn't seem to be a bug in jspm?

**Comment by guybedford** [comment]
Which version of jspm are you running? Note that SystemJS currently only works against jspm 0.16 beta.

**Comment by dvc94ch** [comment]
I cloned both so they should be up to date

**Comment by dvc94ch** [comment]
Incase I wasn't clear, they are up to date :)

**Comment by guybedford** [comment]
I haven't been able to fully replicate unfortunately but I've added a fix in https://github.com/systemjs/systemjs/commit/0565af61f5a8f2ef92fc9a1b2eaf743aee93d510.

**Comment by dvc94ch** [comment]
There some more errors popping up, but I'm not sure they're related to
jspm/systemjs. I'll have to look at it tomorrow...

**Comment by omerts** [comment]
After updating to the latest version, which fixes the problem with __dirname (in windows). I am getting the following error, even after updating the negotiator.js as stated above:
```
Module ./charset not declared as a dependency.
```

**Comment by omerts** [comment]
npm install -g jspm@beta, reinstalling all my packages, and running jspm dl-loader, it works now :)
