### ISSUE TITLE
Support `browserify` as a main override

### ISSUE THREAD

**Issue by guybedford** [jspm/npm#31]
It's just another line like in https://github.com/jspm/npm/blob/master/npm.js#L311.

**Comment by guybedford** [comment]
Included.

**Comment by u9520107** [comment]
@guybedford How do I verify that this is working as intended?
I am seeing jspm attempting to load server side code when the target's package.json have "browser" directive.
More more, the package linker generated by jspm doesn't point to the script specified by "browser".
Currented tested on jspm@0.15.6

**Comment by guybedford** [comment]
@u9520107 thanks - yes this is a bug. The browser mappings aren't being applied to the main entry point or any other external requires. This is something that will be fixed by the new configuration system being rolled out with the next version of SystemJS.

**Comment by u9520107** [comment]
@guybedford awesome! Do you have an eta?

**Comment by guybedford** [comment]
Unfortunately this will take some time. I'd suggest a workaround in the mean time.

**Comment by u9520107** [comment]
Any progress on this issue? Still not being able to simply import mqtt.js through jspm.

**Comment by u9520107** [comment]
@guybedford There is one more issue with mqtt.js
mqtt/lib/connect/index.js
```javascript
(function(process) {
  'use strict';
  var MqttClient = require("../client"),
      url = require("url"),
      xtend = require("xtend"),
      protocols = {},
      protocolList = [];
  if ('browser' !== process.title) {
    protocols.mqtt = require("./tcp");
    protocols.tcp = require("./tcp");
    protocols.ssl = require("./tls");
    protocols.tls = require("./tls");
    protocols.mqtts = require("./tls");
  }
...
```

In the code, even tho the block in the if statement wasn't executed, JSPM loads those modules before executing the code anyway. Those modules are not supposed to be loaded on the browser, and thus ends up with exceptions.

**Comment by guybedford** [comment]
Yes that is a limitation of the way SystemJS loads CommonJS.

The way to handle these cases is by mapping to empty the things you don't want loaded:

```
  jspm install npm:mqtt -o "{map: { './tcp': '@empty' }}"
```

**Comment by u9520107** [comment]
I see... 
Oh well... hopefully these issue will start to ease out when es6 features are hitting the browsers.
Thanks.
