### ISSUE TITLE
`browser` to only apply in browser

### ISSUE THREAD

**Issue by guybedford** [jspm/npm#32]
This is dependent on comprehensive conditional loading support.

**Comment by guybedford** [comment]
This will allow `jspm install npm:express` to work.

**Comment by omerts** [comment]
Is there any progress with this?
We really need this, we are having trouble running server side code.

**Comment by Gaelan** [comment]
Conditional loading is in! Is this enough for this feature to be implemented?

**Comment by guybedford** [comment]
Yes this feature is actually implemented already on the 0.17 development branches.

**Comment by Gaelan** [comment]
YAY! :smile:
