### ISSUE TITLE
"jspm install npm:three" bug

### ISSUE THREAD

**Issue by speigg** [jspm/npm#41]
Unnecessarily adds Buffer and process as dependencies.

**Comment by guybedford** [comment]
Thanks - ok we can improve this by detecting the use of Buffer or Process using proper scope analysis on the tree instead of regular expressions.

**Comment by guybedford** [comment]
Let me know if this seems urgent, but for now I'm prioritising other issues first.

**Comment by speigg** [comment]
That's fine, I can use github:mrdoob/three for now, but npm would be nice eventually as it just downloads the build files.

**Comment by guybedford** [comment]
Duplicate of https://github.com/jspm/npm/issues/55.
