### ISSUE TITLE
Support tarball dependencies

### ISSUE THREAD

**Issue by guybedford** [jspm/npm#44]
Depends on endpoint work at https://github.com/jspm/jspm-cli/issues/424

**Comment by AshleyGrant** [comment]
Has any progress been made to support tarball deps?

**Comment by guybedford** [comment]
Have been going back and fourth on the debate in https://github.com/jspm/jspm-cli/issues/424#issuecomment-84944946. It's not currently prioritised.

**Comment by wichert** [comment]
This is now tracked in jspm/jspm-cli#622 as far as I can see.
