### ISSUE TITLE
Provide useful message for jspm-style dependencies

### ISSUE THREAD

**Issue by guybedford** [jspm/npm#47]
From https://github.com/jspm/jspm-cli/issues/556.

If we install a package here that has a `dependencies: { p: 'jspm:p' }` or something like that (jspm endpoint style), we should throw a useful descriptive error message from within this npm endpoint so the user knows how to correct their dependencies (as it will break down the line in the install process anyway).

**Comment by crisptrutski** [comment]
Closed by 22aec9a163fd4e95e4ba00174c0f892933b93e67
