### ISSUE TITLE
loading superagent

### ISSUE THREAD

**Issue by u9520107** [jspm/npm#50]
I tried to use superagent as is from npm.
Currently it supports browserify via "browser" tag
But instead of specifying a separate main for browser it has this:
```
"main": "./lib/node/index.js",
"browser": {
  "./lib/node/index.js": "./lib/client.js",
  "emitter": "component-emitter",
  "reduce": "reduce-component"
}
```

The jspm generated loader superagent@0.21.0.js file points to './lib/node/index.js', so it doesn't work.
And judging from the installed packages, jspm still takes the dependencies from "dependencies" and doesn't follow "browser".
Is it possible to support packages with these kind of settings?

Currently I fork the project and add jspm dependencies under the "jspm" tag.

**Comment by guybedford** [comment]
Yes support for superagent is being tracked in https://github.com/jspm/registry/issues/203. Supporting the non-browser case is dependent on conditional loading in SystemJS, a big feature change, which is being worked on.
