### ISSUE TITLE
support bower.json

### ISSUE THREAD

**Issue by lookfirst** [jspm/npm#51]
The github endpoint supports finding dependencies in bower.json, but the npm endpoint doesn't. It would be nice if these two endpoints were more in line with each other. Possibly even share a lot of the same base codebase?

This caused this confusion: https://github.com/angular/angular/issues/944

**Comment by guybedford** [comment]
@lookfirst the treatment is designed to be different. The point being that `npm install angular` should provide exactly the same interface as `jspm install npm:angular`. To look at bower.json would be to break the contract we have with matching npm behaviour.

**Comment by lookfirst** [comment]
Sigh, I wish you hadn't closed this. It is a real issue. I'm only asking you to look at bower.json if there is no dependencies in package.json and a bower.json exists.

Explain this line in the code: https://github.com/jspm/npm/blob/master/npm.js#L669

// convert NodeJS or **Bower** dependencies into jspm-compatible dependencies

**Comment by guybedford** [comment]
Why not just install `github:angular/angular` here? That's meant to be the bower source anyway.

**Comment by lookfirst** [comment]
Why should it matter where I install angular from?

Do you realize how much confusion this will cause people to have to figure out where to install angular from in order to make their project work?

I gave you a concrete example in the chat room:

https://github.com/angular/material-start/blob/es6/app/config.js

If I add a single npm based dependency to that project that has a package.json dependency on angular, everything will blow up and stop working.

**Comment by 2fd** [comment]
Hi @lookfirst,
tries with https://www.npmjs.org/package/jspm-bower-endpoint

**Comment by lookfirst** [comment]
@2fd rad! I didn't find that before. I've added it to this page: https://github.com/jspm/jspm-cli/wiki/Community-Projects
