### ISSUE TITLE
Cross-package JSON resolutions

### ISSUE THREAD

**Issue by guybedford** [jspm/npm#52]
To allow JSON loading to work across packages, it could be worth creating a js entry point for JSON files that loads the JSON file with the plugin.

**Comment by geelen** [comment]
Do you mean this could work by adding a line to `config.js` along the lines of:

```js
System.config({
  "paths": {
     "autoprefixer-core/lib/data": "npm:autoprefixer-core@5.1.8/lib/data.json!"
  }
});
```

Or is editing `config.js` not enough?

**Comment by guybedford** [comment]
Yes that is exactly the principle, only it would be map config.

This will definitely be included, but I'm waiting for a SystemJS upgrade to drive this with. Working on it honest.

**Comment by geelen** [comment]
Wait, so I can fix my bug just by adding a bunch of lines to the map config? Gonna try that...

**Comment by guybedford** [comment]
Sure, just let me know if you need help with getting the exact config.

**Comment by geelen** [comment]
Yeah, I can't figure it out. This is the file which 404s

```
http://localhost:8081/jspm_packages/npm/caniuse-db@1.0.30000111/data.js
```

For a file referenced by:

```js
require("caniuse-db/data").agents
```

I tried a bunch of combos but can't get them to work.

Thanks dude.

**Comment by guybedford** [comment]
Did you try `map: { 'caniuse-db/data': 'npm:caniuse-db@1.0.30000111/data.json!' }`?

Which module is making this request in the first place?

**Comment by guybedford** [comment]
We can also get an override set up for this as well which may be even better.

**Comment by geelen** [comment]
Still couldn't get this going. Could get the `map` setting to work if I directly included the path `caniuse-db/data`, but not if that path was internal to another dependency. So I deleted autoprefixer from my project. I think I'll make a plugin-autoprefixer (using my fancy new [plugin-postcss](https://github.com/geelen/plugin-postcss)) once we can solve this.

Btw, is the change happening where you won't need `!` at the end of a path to activate a plugin? I know that'll mean you need `.js` on the end of all your local paths but that seems ok, right?

**Comment by guybedford** [comment]
Yes the map has to be added to each dependency using it unfortunately here.

`!` will still be supported, but it will be possible not to use it and setting plugins via extension config instead.

**Comment by geelen** [comment]
For the record, starting a new project, I wish `.js` was required. I keep adding it by mistake on local paths. It'd be kinda neat if anything starting with `.` (i.e. a local path) defaulted to treating the extension as the plugin. Not sure if there's a better issue for me to be adding my 2c to though :)

**Comment by geelen** [comment]
Ok, absolutely got this figured out, and god it's a pain! :)

https://github.com/geelen/friendlier-more-powerful/blob/62a54974a7f6c5cd8d9d7c4b887b208db897a077/config.js#L1124-L1243

In the end I hit another problem with cssnext and decided to just roll with vanilla (but live-reloaded) CSS for now.

**Comment by guybedford** [comment]
This is the most impressive map configuration I've seen yet!

It may be slightly simpler to do:

```javascript
jspm install npm:autoprefixer-core@5.1.11 -o "{ map: { 'caniuse-db/data': 'npm:caniuse-db@1.0.30000145/data.json!', 'caniuse-db/features-json': 'npm:caniuse-db@1.0.30000145/features-json' } }"
```
respectively for each library.

**Comment by guybedford** [comment]
Oh wait I see the issue, apologies, yes we need wildcard config here :)

**Comment by MadLittleMods** [comment]
:+1: I am really in need of `autoprefixer-core`.

I am unable to get [geelen's fix](https://github.com/jspm/npm/issues/52#issuecomment-96428837) working. `System.map` is just a empty object for me even after `System.config({"map": {}})` in `config.js`. When logging `System.map` in the browser though, it seems to be in tact so I am not sure what is going on.

**Comment by MadLittleMods** [comment]
Finally figured this out for myself :grinning: 

geelen's fix is incomplete and tripped me up because I was using more compatibility meaning, more json files that were not mapped and I was still getting errors. 

It is also a bit frustrating when SystemJS/JSPM overwrites and mangles the `foreach` snippet over and over but it is still workable. It is a bit weird how `System.map` was a empty object when bundling/unbundling.

---

### Solution

I made a [gulp task](https://github.com/MadLittleMods/postcss-css-variables/blob/ab2f6484fbc16bdd5c42ae17533374e2eab617d2/playground/gulpfile.js#L91) that loops through all of the json files in `caniuse-db` and generates a json file map from the `caniuse-db` json file references to a json banged version just as guy bedford and geelen brought up.

You can find a version of the [json file that gulp task output here](https://github.com/MadLittleMods/postcss-css-variables/blob/ab2f6484fbc16bdd5c42ae17533374e2eab617d2/playground/caniuse-db-json-systemjs-paths.json). Just copy those entries under `npm:autoprefixer-core@5.1.11` and `npm:browserslist@0.2.0` in `config.js`

**Comment by geelen** [comment]
@MadLittleMods that is pretty brilliant.

**Comment by geelen** [comment]
@guybedford now we have wildcard config, is there a simpler approach available to us?

**Comment by MadLittleMods** [comment]
@geelen I don't think so :( - See the [conversation here](https://gitter.im/systemjs/systemjs?at=55708d93463d0c7c066e12f9)

**Comment by geelen** [comment]
Does that mean that JSPM just hasn't had its 0.17 release yet? Or am I missing something?

**Comment by guybedford** [comment]
This release is a 0.17 SystemJS against a 0.16 jspm (confusing I know). The jspm config upgrade will be in 0.17, because using the new SystemJS configuration system in jspm is firstly a big job, and secondly and more importantly, not backwards-compatible with the CDN. That is, jspm 0.17 will come with a new CDN and be served over jsDelivr for the next few years with full backwards compatibility (an incredibly daunting thing to plan) with some luck (if @jimaek still lets me do this after all this time :)

**Comment by jimaek** [comment]
@guybedford Sure, just ping me with whatever you need

**Comment by guybedford** [comment]
@jimaek thanks so much! Still have the previous proxy working ok, so will be developing on that over the coming months.

**Comment by teohhanhui** [comment]
It's not working (or am I doing it wrong?). Please help.

I have

```js
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  map: {
    "npm:language-tags@1.0.3": {
      "language-subtag-registry": "npm:language-subtag-registry@0.3.11",
      "language-subtag-registry/data/json/index": "npm:language-subtag-registry@0.3.11/data/json/index.json!",
      "language-subtag-registry/data/json/registry": "npm:language-subtag-registry@0.3.11/data/json/registry.json!",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
  }
);
```

but the `require('language-subtag-registry/data/json/index')` from [language-tags](https://github.com/mattcg/language-tags/blob/7e2217af4e422a1631550a3118894c2d8b0c8127/lib/index.js#L14) tries to load `/jspm_packages/npm/language-subtag-registry@0.3.11/data/json/index.json!.js`

**Comment by MadLittleMods** [comment]
@teohhanhui I have not been able to get any sort of solution for JSON loading in v0.15.x+.

**Comment by teohhanhui** [comment]
I got it working by providing the override during `jspm install` as per https://github.com/jspm/npm/issues/52#issuecomment-96828258

**Comment by teohhanhui** [comment]
Also, you should publish your override to [jspm/registry](https://github.com/jspm/registry)

From https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#testing-configuration
> Once tested the exact override can then be included in the [registry with a pull request](https://github.com/jspm/registry#submitting-a-package-override).

**Comment by guybedford** [comment]
These have been supported for a while in jspm 0.17.
