### ISSUE TITLE
Scoped package support & bug fixes

### ISSUE THREAD

**Issue by brianc** [jspm/npm#63]
I have a scoped package in the public npm registry: `@brianc/http` (creative name, I know) [link to npm here](https://www.npmjs.com/package/@brianc/http)

I am running `jspm install npm:@brianc/http` and getting the following:

```
err Repo npm:@brianc/http not found!

```

What am I doing wrong? :(

**Comment by guybedford** [comment]
Thanks - we need to do some more testing here to get these to work. Should be able to get it in this week.

**Comment by brianc** [comment]
Ah thanks! Sorry - I thought I was just overlooking something.  I appreciate you looking at it. :)
