### ISSUE TITLE
Improve robustness of .npmrc imports

### ISSUE THREAD

**Issue by crisptrutski** [jspm/npm#67]
Some or all of this may be YAGNI, but just pointing out what I've noticed.

1. Only user path is checked, out of the 4 possible locations support by npm at this time
2. Assumes only one file exists, no "cascading" at a per-property level
3. Vulnerable to changes in precedence or locations in future npm version
4. Vulnerable to changes in format in future npm versions

My solution to all of the above would be to shell out to `npm config get ..` if it exists, then the only brittleness is that API changing (doubtful). The existing behaviour could be maintained as a fallback (potentially updated to handle 1 and 2 above)

@guybedford

**Comment by crisptrutski** [comment]
Additional, seemingly more pressing issues:

1. Reads from *first* key entries (no attempt to match registry scope)
2. Does not support `username` and `_password` keys for auth

**Comment by crisptrutski** [comment]
Using `npm config get` won't work for `_auth` and `_password`, due to sensible precautions. So 3 and 4 will just need to be (small) maintenance risks

**Comment by crisptrutski** [comment]
@guybedford one more problem, we should expand `${ENV}` style variables inside the npmrc files.

**Comment by guybedford** [comment]
Let's wait till we hit it.

**Comment by crisptrutski** [comment]
Created backlog here #71
