### ISSUE TITLE
Add support for npm _authToken

### ISSUE THREAD

**Issue by guybedford** [jspm/npm#74]
Just need to work out how this works - is it a password like GitHub, or is it not basic auth in HTTPS and a special header?

Contributions welcome.

**Comment by lookfirst** [comment]
Or just use npm to do the downloads. ;-)

**Comment by guybedford** [comment]
Finally found the header - https://github.com/npm/npm-registry-client/blob/master/lib/authify.js#L6.

**Comment by guybedford** [comment]
Added and supported in https://github.com/jspm/npm/commit/226de7b8a6e25b9c4d054275e5254edcb360ad8c.
