### ISSUE TITLE
Array main throws

### ISSUE THREAD

**Issue by guybedford** [jspm/npm#75]
Example - `npm:bootstrap-treeview`.

**Comment by guybedford** [comment]
Already fixed on master.

**Comment by kezugo** [comment]
I think there is similar thing on 0.17.0-beta.12 - systemConfig.main.substr is not a function when installing it via npm:bootstrap-treeview

**Comment by guybedford** [comment]
@kezugo thanks, added https://github.com/jspm/npm/commit/ed82b7ff695c1f2e9e2f5a0f71f69730236133ed.
