### ISSUE TITLE
CDN changes 0.4.11-rc4 to 0.4c4

### ISSUE THREAD

**Issue by letmaik** [jspm/npm#99]
In the [package.json](https://github.com/Reading-eScience-Centre/leaflet-coverage/blob/master/package.json#L49), the version is given as `"c3": "npm:c3@^0.4.11-rc4"` however at
https://github.jspm.io/Reading-eScience-Centre/leaflet-coverage@master/popups/ProfilePlot.js the CDN replaced it with `npm:c3@0.4c4` which seems broken and also leads to a 404. I guess it's a subtle bug in version processing.

**Comment by guybedford** [comment]
Moved to https://github.com/jspm/jspm.io/issues/52.
